export enum AppErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  RATE_LIMITED = 'RATE_LIMITED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  FORBIDDEN_ROLE = 'FORBIDDEN_ROLE',
  MUST_CHANGE_PASSWORD = 'MUST_CHANGE_PASSWORD',
  LOGIN_ID_TAKEN = 'LOGIN_ID_TAKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_CURRENT_PASSWORD = 'WRONG_CURRENT_PASSWORD',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
